import type { AstraWork } from "./astra-feed";

export const ASTRA_FEED_EXTRA: AstraWork[] = [
  {
    id: "architecture-studio",
    title: "Architecture Studio",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "浏览器里的建筑工作室：调材质、光线和体块，官方页可玩。",
    playUrl: "https://architecture-studio.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/architecture-studio",
    cover: "/astra/architecture-studio.webp",
    coverRemote: "https://developers.openai.com/showcase/architecture-studio/cover.webp",
  },
  {
    id: "asterism",
    title: "Asterism",
    creator: "Charlie Guo",
    handle: "charlieg",
    kind: "game",
    source: "official",
    blurb: "用有限的命名星组成星座，点亮夜空。",
    playUrl: "https://asterism.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/asterism",
    cover: "/astra/asterism.jpg",
    coverRemote: "https://developers.openai.com/showcase/asterism/cover.webp",
  },
  {
    id: "backroom-center",
    title: "Backroom Center: Corrupted",
    creator: "Thomas Ricouard",
    handle: "Dimillian",
    kind: "game",
    source: "official",
    blurb: "第一人称数据中心迷宫，程序化走廊加 VHS 劣化。",
    playUrl: "https://backroom-center-corrupted.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/backroom-center-corrupted",
    cover: "/astra/backroom-center.jpg",
    coverRemote: "https://developers.openai.com/showcase/backroom-center-corrupted/cover.webp",
  },
  {
    id: "below-the-surface",
    title: "Below the Surface",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "可下潜的海洋剖面，官方 3D 场景。",
    playUrl: "https://below-the-surface-ocean.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/below-the-surface",
    cover: "/astra/below-the-surface.webp",
    coverRemote: "https://developers.openai.com/showcase/below-the-surface/cover.webp",
  },
  {
    id: "biome-lab",
    title: "Biome Lab",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "可调生态的程序化 terrarium 沙盒。",
    playUrl: "https://interactive-studies-56.openai.chatgpt.site/biome-lab/",
    sourceUrl: "https://developers.openai.com/showcase/biome-lab",
    cover: "/astra/biome-lab.jpg",
    coverRemote: "https://developers.openai.com/showcase/biome-lab/cover.webp",
  },
  {
    id: "codex-modeling-studio",
    title: "Codex Modeling Studio",
    creator: "Eric Provencher",
    handle: "eProvencher",
    kind: "3d",
    source: "official",
    blurb: "浏览器里摆 3D 形体、看光影的建模台。",
    playUrl: "https://codex-modeling-studio.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/codex-modeling-studio",
    cover: "/astra/codex-modeling-studio.jpg",
    coverRemote: "https://developers.openai.com/showcase/codex-modeling-studio/cover.webp",
  },
  {
    id: "codex-pet-arena",
    title: "Codex Pet Arena",
    creator: "Gabriel Chua",
    handle: "gabrielchua",
    kind: "game",
    source: "official",
    blurb: "宠物平台竞技场：吃代币变大，把对手撞飞。",
    playUrl: "https://codex-pet-arena-20260709.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/codex-pet-arena",
    cover: "/astra/codex-pet-arena.jpg",
    coverRemote: "https://developers.openai.com/showcase/codex-pet-arena/cover.webp",
  },
  {
    id: "courtyard-house",
    title: "Courtyard House",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "可走的庭院住宅，调时间和材质。",
    playUrl: "https://alder-courtyard-house.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/courtyard-house",
    cover: "/astra/courtyard-house.webp",
    coverRemote: "https://developers.openai.com/showcase/courtyard-house/cover.webp",
  },
  {
    id: "crossword-desk",
    title: "Crossword Desk",
    creator: "Aaron Levine",
    handle: "aaronlevine",
    kind: "game",
    source: "official",
    blurb: "浏览器填字台，官方页可玩。",
    playUrl: "https://crossword-desk-studio.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/crossword-desk",
    cover: "/astra/crossword-desk.webp",
    coverRemote: "https://developers.openai.com/showcase/crossword-desk/cover.webp",
  },
  {
    id: "cubecade",
    title: "Cubecade",
    creator: "Niall McCormack",
    handle: "niall",
    kind: "game",
    source: "official",
    blurb: "魔方式 3D 方块解谜。",
    playUrl: "https://cubecade.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/cubecade-rubiks",
    cover: "/astra/cubecade.jpg",
    coverRemote: "https://developers.openai.com/showcase/cubecade-rubiks/cover.webp",
  },
  {
    id: "field-day",
    title: "Field Day",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "野餐用品店面，带可交互商品和礼篮。",
    playUrl: "https://store-fronts-56.openai.chatgpt.site/field-day/",
    sourceUrl: "https://developers.openai.com/showcase/field-day",
    cover: "/astra/field-day.jpg",
    coverRemote: "https://developers.openai.com/showcase/field-day/cover.webp",
  },
  {
    id: "frame-studio",
    title: "Frame Studio",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "给 3D 角色摆姿势、做定格动画的工作台。",
    playUrl: "https://frame-studio-motion.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/frame-studio",
    cover: "/astra/frame-studio.webp",
    coverRemote: "https://developers.openai.com/showcase/frame-studio/cover.webp",
  },
  {
    id: "glass-towers",
    title: "Glass Towers",
    creator: "Eric Provencher",
    handle: "eProvencher",
    kind: "game",
    source: "official",
    blurb: "半透明体块堆叠的物理平衡游戏。",
    playUrl: "https://glass-towers.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/glass-towers",
    cover: "/astra/glass-towers.jpg",
    coverRemote: "https://developers.openai.com/showcase/glass-towers/cover.webp",
  },
  {
    id: "kiln",
    title: "Kiln",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "陶瓷店面，杯子可旋转看釉面。",
    playUrl: "https://store-fronts-56.openai.chatgpt.site/kiln/",
    sourceUrl: "https://developers.openai.com/showcase/kiln",
    cover: "/astra/kiln.jpg",
    coverRemote: "https://developers.openai.com/showcase/kiln/cover.webp",
  },
  {
    id: "material-lab",
    title: "Material Lab",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "实时测材质、灯光和形体的 3D 实验室。",
    playUrl: "https://interactive-studies-56.openai.chatgpt.site/material-lab/",
    sourceUrl: "https://developers.openai.com/showcase/material-lab",
    cover: "/astra/material-lab.jpg",
    coverRemote: "https://developers.openai.com/showcase/material-lab/cover.webp",
  },
  {
    id: "nightjar",
    title: "Nightjar Listening Room",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "夜间听音室，空间和器材可转。",
    playUrl: "https://nightjar-listening-room.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/nightjar-listening-room",
    cover: "/astra/nightjar.webp",
    coverRemote: "https://developers.openai.com/showcase/nightjar-listening-room/cover.webp",
  },
  {
    id: "paper-glider",
    title: "Paper Glider",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "game",
    source: "official",
    blurb: "在程序化阳光房间里飞纸飞机。",
    playUrl: "https://paper-glider-56.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/paper-glider",
    cover: "/astra/paper-glider.jpg",
    coverRemote: "https://developers.openai.com/showcase/paper-glider/cover.webp",
  },
  {
    id: "pattern-studio",
    title: "Pattern Studio",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "三维图案工作室，调重复纹样和材质。",
    playUrl: "https://pattern-studio.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/pattern-studio",
    cover: "/astra/pattern-studio.webp",
    coverRemote: "https://developers.openai.com/showcase/pattern-studio/cover.webp",
  },
  {
    id: "stop-motion-desk",
    title: "Stop-Motion Desk",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "给 3D 角色摆帧的定格动画桌。",
    playUrl: "https://stop-motion-desk.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/stop-motion-desk",
    cover: "/astra/stop-motion-desk.webp",
    coverRemote: "https://developers.openai.com/showcase/stop-motion-desk/cover.webp",
  },
  {
    id: "sunday-table",
    title: "Sunday Table",
    creator: "James Sun",
    handle: "jamessun",
    kind: "3d",
    source: "official",
    blurb: "周日餐桌场景，菜品和器皿可看。",
    playUrl: "https://sundaytable.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/sunday-table",
    cover: "/astra/sunday-table.jpg",
    coverRemote: "https://developers.openai.com/showcase/sunday-table/cover.webp",
  },
  {
    id: "terrain-mixer",
    title: "Terrain Mixer",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "程序化地形，三维视图和分析视图同步。",
    playUrl: "https://interactive-studies-56.openai.chatgpt.site/terrain-mixer/",
    sourceUrl: "https://developers.openai.com/showcase/terrain-mixer",
    cover: "/astra/terrain-mixer.jpg",
    coverRemote: "https://developers.openai.com/showcase/terrain-mixer/cover.webp",
  },
  {
    id: "tidal-house",
    title: "Tidal House",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "潮汐边的retreat住宅，可绕行观看。",
    playUrl: "https://tidal-house-retreat.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/tidal-house",
    cover: "/astra/tidal-house.webp",
    coverRemote: "https://developers.openai.com/showcase/tidal-house/cover.webp",
  },
  {
    id: "tiny-rails",
    title: "Tiny Rails Rollercoaster",
    creator: "VB Srivastav",
    handle: "reach_vb",
    kind: "game",
    source: "official",
    blurb: "迷你过山车，八条路线和多种驾驶模式。",
    playUrl: "https://sol-on-rails.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/tiny-rails-rollercoaster",
    cover: "/astra/tiny-rails.webp",
    coverRemote: "https://developers.openai.com/showcase/tiny-rails-rollercoaster/cover.webp",
  },
  {
    id: "type-field",
    title: "Type Field",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "三维字体展览场，字母是可绕行的雕塑。",
    playUrl: "https://type-field-exhibition.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/type-field",
    cover: "/astra/type-field.webp",
    coverRemote: "https://developers.openai.com/showcase/type-field/cover.webp",
  },
  {
    id: "verdant-market",
    title: "Verdant Market",
    creator: "Niall McCormack",
    handle: "niall",
    kind: "3d",
    source: "official",
    blurb: "蔬果杂货店面，货架和商品是三维的。",
    playUrl: "https://verdant-market-grocery.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/verdant-market",
    cover: "/astra/verdant-market.jpg",
    coverRemote: "https://developers.openai.com/showcase/verdant-market/cover.webp",
  },
  {
    id: "webroom",
    title: "Webroom",
    creator: "Matias Castello",
    handle: "mcastello",
    kind: "3d",
    source: "official",
    blurb: "可走进去的网页房间。",
    playUrl: "https://webroom.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/webroom",
    cover: "/astra/webroom.webp",
    coverRemote: "https://developers.openai.com/showcase/webroom/cover.webp",
  },
  {
    id: "minitown",
    title: "MiniTown",
    creator: "Thomas Ricouard",
    handle: "Dimillian",
    kind: "game",
    source: "official",
    blurb: "袖珍小镇：分区生长、居民通勤、夜里亮灯。",
    playUrl: "https://minitown-cozy-sim.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/minitown",
    cover: "/astra/minitown.jpg",
    coverRemote: "https://developers.openai.com/showcase/minitown/cover.webp",
  },
  {
    id: "phantasy-codex-adventure",
    title: "Phantasy Codex Adventure",
    creator: "Thomas Ricouard",
    handle: "Dimillian",
    kind: "game",
    source: "official",
    blurb: "持久复古动作 RPG，程序化世界和共享排名。",
    playUrl: "https://phantasy-codex-adventure.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/phantasy-codex-adventure",
    cover: "/astra/phantasy-codex-adventure.jpg",
    coverRemote: "https://developers.openai.com/showcase/phantasy-codex-adventure/cover.webp",
  },
  {
    id: "phantasy-codex-online",
    title: "Phantasy Codex Online",
    creator: "Thomas Ricouard",
    handle: "Dimillian",
    kind: "game",
    source: "official",
    blurb: "带城镇、掉落和世界层级的浏览器动作 RPG。",
    playUrl: "https://phantasy-codex-online.openai.chatgpt.site/",
    sourceUrl: "https://the-infinite-build.openai.chatgpt.site/",
    cover: "/astra/phantasy-codex-online.jpg",
    coverRemote: "https://developers.openai.com/showcase/phantasy-codex-adventure/cover.webp",
  },
  {
    id: "ridge-pack",
    title: "Ridge Pack",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "背包店面，可交互装箱指南。",
    playUrl: "https://ridge-pack.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/ridge-pack",
    cover: "/astra/ridge-pack.jpg",
    coverRemote: "https://developers.openai.com/showcase/ridge-pack/cover.webp",
  },
  {
    id: "scent-cartography",
    title: "Scent Cartography",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "植物香氛店，自己调一瓶气味。",
    playUrl: "https://store-fronts-56.openai.chatgpt.site/scent-cartography/",
    sourceUrl: "https://developers.openai.com/showcase/scent-cartography",
    cover: "/astra/scent-cartography.jpg",
    coverRemote: "https://developers.openai.com/showcase/scent-cartography/cover.webp",
  },
  {
    id: "paperie",
    title: "Paperie",
    creator: "James Sun",
    handle: "jamessun",
    kind: "3d",
    source: "official",
    blurb: "立体贺卡工作室，纸面可翻可写。",
    playUrl: "https://paperie-webmcp-greeting-cards.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/paperie",
    cover: "/astra/paperie.jpg",
    coverRemote: "https://developers.openai.com/showcase/paperie/cover.webp",
  },
  {
    id: "fieldwork-12",
    title: "Fieldwork // 12",
    creator: "Justin Rushing",
    handle: "jrushing",
    kind: "3d",
    source: "official",
    blurb: "田间节拍机，旋钮和波形都在三维台上。",
    playUrl: "https://fieldwork-beat-machine.openai.chatgpt.site/",
    sourceUrl: "https://developers.openai.com/showcase/ko-field-beat-machine",
    cover: "/astra/fieldwork-12.webp",
    coverRemote: "https://developers.openai.com/showcase/ko-field-beat-machine/cover.webp",
  },
  {
    id: "waveform-studio",
    title: "Waveform Studio",
    creator: "Katia Gil Guzman",
    handle: "katiagg",
    kind: "3d",
    source: "official",
    blurb: "把音频变成可调波形雕塑。",
    playUrl: "https://interactive-studies-56.openai.chatgpt.site/waveform-studio/",
    sourceUrl: "https://developers.openai.com/showcase/waveform-studio",
    cover: "/astra/waveform-studio.jpg",
    coverRemote: "https://developers.openai.com/showcase/waveform-studio/cover.webp",
  },
  {
    id: "seven-little-worlds",
    title: "Seven Little Worlds",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "Astra 评测里的七个小行星世界。",
    playUrl: "https://signals.forwardfuture.com/astra-review/demos/seven-little-worlds/index.html",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/seven-little-worlds.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/seven-worlds.webp",
  },
  {
    id: "cloudtop-chaos",
    title: "Cloudtop Chaos",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "game",
    source: "astra-review",
    blurb: "云上障碍赛，Astra 评测里的 Fall Guys 风一局。",
    playUrl: "https://royal-pebble-6azj.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/cloudtop-chaos.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/obstacle-course.jpg",
  },
  {
    id: "newhaven",
    title: "Newhaven",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "ASCII 搭起来的整座城，可走进去。",
    playUrl: "https://signals.forwardfuture.com/astra-review/demos/newhaven/index.html",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/newhaven.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/newhaven.webp",
  },
  {
    id: "afterhours",
    title: "AFTERHOURS",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "夜间城市空间，Astra 评测可玩 demo。",
    playUrl: "https://signals.forwardfuture.com/astra-review/demos/afterhours/index.html",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/afterhours.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/afterhours.webp",
  },
  {
    id: "commons",
    title: "COMMONS",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "公共空间三维场景，评测磁贴直达。",
    playUrl: "https://crystal-pagoda-b6ka.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/commons.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/commons.webp",
  },
  {
    id: "little-planet-berman",
    title: "Little Planet",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "一颗可绕行的小球世界。",
    playUrl: "https://signals.forwardfuture.com/astra-review/demos/little-planet/index.html",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/little-planet-berman.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/little-planet.webp",
  },
  {
    id: "pip-orchard",
    title: "Pip & Orchard",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "game",
    source: "astra-review",
    blurb: "果园小品，评测 here.now 托管。",
    playUrl: "https://grassy-nirvana-xwhj.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/pip-orchard.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/pip.webp",
  },
  {
    id: "dgx-spark",
    title: "DGX Spark",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "DGX Spark 机箱三维拆解。",
    playUrl: "https://presto-basin-gd5w.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/dgx-spark.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/dgx.webp",
  },
  {
    id: "quack-club",
    title: "Quack Club",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "game",
    source: "astra-review",
    blurb: "鸭子俱乐部小游戏。",
    playUrl: "https://vast-vortex-dg57.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/quack-club.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/quack.webp",
  },
  {
    id: "galaxy-z-fold7",
    title: "Galaxy Z Fold7",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "折叠屏产品三维展示。",
    playUrl: "https://zephyr-haven-cepc.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/galaxy-z-fold7.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/fold.webp",
  },
  {
    id: "model-y",
    title: "Model Y",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "Model Y 车身三维浏览。",
    playUrl: "https://marble-ferry-da7y.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/model-y.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/modely.webp",
  },
  {
    id: "pelagic",
    title: "PELAGIC",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "远洋三维场景。",
    playUrl: "https://russet-onyx-z85r.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/pelagic.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/pelagic.webp",
  },
  {
    id: "form-factor",
    title: "FORM / FACTOR",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "工业造型三维研究。",
    playUrl: "https://blazing-lichen-3v5s.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/form-factor.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/form.webp",
  },
  {
    id: "the-threshold",
    title: "THE THRESHOLD",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "门槛空间 walkthrough。",
    playUrl: "https://signals.forwardfuture.com/astra-review/demos/threshold/index.html",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/the-threshold.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/threshold.webp",
  },
  {
    id: "prism-berman",
    title: "PRISM",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "棱镜立方体交互。",
    playUrl: "https://signals.forwardfuture.com/astra-review/demos/cube/index.html",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/prism-berman.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/cube.jpg",
  },
  {
    id: "needle-haystack",
    title: "Needle in a Haystack",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "game",
    source: "astra-review",
    blurb: "草垛里找针的交互小品。",
    playUrl: "https://signals.forwardfuture.com/astra-review/demos/needle/index.html",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/needle-haystack.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/needle.webp",
  },
  {
    id: "ratstronaut-riot",
    title: "Ratstronaut Riot!",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "game",
    source: "astra-review",
    blurb: "老鼠宇航员闹事，评测游戏磁贴。",
    playUrl: "https://tropic-wreath-q2hc.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/ratstronaut-riot.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/rat.webp",
  },
  {
    id: "verdant-bastion",
    title: "Verdant Bastion",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "绿色堡垒三维场景。",
    playUrl: "https://signals.forwardfuture.com/astra-review/demos/verdant-bastion/index.html",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/verdant-bastion.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/verdant.webp",
  },
  {
    id: "vice-signal",
    title: "VICE // SIGNAL",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "浏览器里的信号台。",
    playUrl: "https://quartz-igloo-d2ah.here.now/browser/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/vice-signal.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/vice.webp",
  },
  {
    id: "moon-swallowed-names",
    title: "The Moon That Swallowed Our Names",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "可翻的漫画卷，月亮吞掉名字。",
    playUrl: "https://signals.forwardfuture.com/astra-review/demos/manga/index.html",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/moon-swallowed-names.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/manga.webp",
  },
  {
    id: "browser-in-action",
    title: "Browser in Action",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "Astra 操作浏览器的可视化回放。",
    playUrl: "https://open-nebula-akqx.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/browser-in-action.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/browser.webp",
  },
  {
    id: "chronoshift",
    title: "CHRONOSHIFT",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "game",
    source: "astra-review",
    blurb: "时间错位题材交互。",
    playUrl: "https://regal-poplar-5ay6.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/chronoshift.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/chrono.webp",
  },
  {
    id: "periapsis",
    title: "PERIAPSIS",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "近拱点轨道三维。",
    playUrl: "https://unfold-valley-ydt7.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/periapsis.webp",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/periapsis.webp",
  },
  {
    id: "glassbox",
    title: "GLASSBOX",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "玻璃盒实验装置。",
    playUrl: "https://saffron-spirit-3a8y.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/glassbox.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/glassbox.webp",
  },
  {
    id: "evidence-room",
    title: "THE EVIDENCE ROOM",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "证据室阅读器，空间里翻档案。",
    playUrl: "https://lively-rocket-95s2.here.now/reader/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/evidence-room.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/evidence.webp",
  },
  {
    id: "polyrhythm",
    title: "POLYRHYTHM",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "复节奏可视化。",
    playUrl: "https://calm-signal-zmp2.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/polyrhythm.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/poly.webp",
  },
  {
    id: "dead-letter",
    title: "DEAD LETTER",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "game",
    source: "astra-review",
    blurb: "死信局叙事交互。",
    playUrl: "https://marine-warden-2hd5.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/dead-letter.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/deadletter.webp",
  },
  {
    id: "switchyard",
    title: "SWITCHYARD",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "编组站三维系统。",
    playUrl: "https://cedar-plover-r47w.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/switchyard.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/switch.webp",
  },
  {
    id: "neural-observatory",
    title: "NEURAL OBSERVATORY",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "神经观测台三维装置。",
    playUrl: "https://wistful-rocket-bbsd.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/neural-observatory.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/neural.webp",
  },
  {
    id: "launchpad",
    title: "LAUNCHPAD",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "发射台看板，三维面板。",
    playUrl: "https://blazing-forge-tfh2.here.now/board/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/launchpad.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/launch.webp",
  },
  {
    id: "spin-cycle",
    title: "Spin Cycle",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "game",
    source: "astra-review",
    blurb: "旋转循环小游戏。",
    playUrl: "https://dusty-cliff-y6me.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/spin-cycle.jpg",
    coverRemote: "https://signals.forwardfuture.com/astra-review/projects/spin.webp",
  },
  {
    id: "buzz-game-lab",
    title: "Buzz Game Lab",
    creator: "sora-jp",
    handle: "sora-jp",
    kind: "game",
    source: "community",
    blurb: "日式免登录小游戏合集，短挑战和分数循环。",
    playUrl: "https://buzz-game-lab.sora-jp.chatgpt.site/",
    sourceUrl: "https://github.com/pyth0nb3st/awesome-chatgpt-sites",
    cover: "/astra/buzz-game-lab.jpg",
    coverRemote: "",
  },
  {
    id: "dailies",
    title: "Dailies",
    creator: "Jon Abrams",
    handle: "jonabrams",
    kind: "game",
    source: "community",
    blurb: "浏览器逻辑谜题：Net、温度计、斜线、点灯。",
    playUrl: "https://dailies.jonabrams.chatgpt.site/",
    sourceUrl: "https://dailies.jonabrams.chatgpt.site/",
    cover: "/astra/dailies.jpg",
    coverRemote: "",
  },
  {
    id: "mabomabo",
    title: "MaboMabo",
    creator: "LUCIAN LAMP",
    handle: "lucianlamp",
    kind: "game",
    source: "community",
    blurb: "四灵连锁消消乐，fever 和排行榜。",
    playUrl: "https://mabomabo.lucianlamp.chatgpt.site/",
    sourceUrl: "https://mabomabo.lucianlamp.chatgpt.site/",
    cover: "/astra/mabomabo.jpg",
    coverRemote: "",
  },
  {
    id: "pechipechi-awake",
    title: "Pechipechi Awake",
    creator: "neneneai",
    handle: "neneneai",
    kind: "game",
    source: "community",
    blurb: "像素生存，360 度移动和无尽战斗。",
    playUrl: "https://pechipechi-awake.neneneai.chatgpt.site/",
    sourceUrl: "https://pechipechi-awake.neneneai.chatgpt.site/",
    cover: "/astra/pechipechi-awake.jpg",
    coverRemote: "",
  },
  {
    id: "cubewild",
    title: "方境 / Cubewild",
    creator: "xiaohaoyopt0",
    handle: "xiaohaoyopt0",
    kind: "game",
    source: "community",
    blurb: "浏览器体素沙盒，创造模式和本地存档。",
    playUrl: "https://fangjing-voxel-71026.xiaohaoyopt0.chatgpt.site/",
    sourceUrl: "https://fangjing-voxel-71026.xiaohaoyopt0.chatgpt.site/",
    cover: "/astra/cubewild.jpg",
    coverRemote: "",
  },
  {
    id: "novacade-slingshift",
    title: "Slingshift",
    creator: "NovaCade",
    handle: "thatgamer253",
    kind: "game",
    source: "community",
    blurb: "把碎片钩进轨道再甩出去的动作 roguelite。",
    playUrl: "https://novacade.thatgamer253.chatgpt.site/games/slingshift/",
    sourceUrl: "https://novacade.thatgamer253.chatgpt.site/",
    cover: "/astra/novacade-slingshift.jpg",
    coverRemote: "",
  },
  {
    id: "novacade-brickfuse",
    title: "Brickfuse",
    creator: "NovaCade",
    handle: "thatgamer253",
    kind: "game",
    source: "community",
    blurb: "打砖块同时现场编 techno / hip-hop。",
    playUrl: "https://novacade.thatgamer253.chatgpt.site/games/brickfuse/",
    sourceUrl: "https://novacade.thatgamer253.chatgpt.site/",
    cover: "/astra/novacade-brickfuse.jpg",
    coverRemote: "",
  },
  {
    id: "novacade-bumper",
    title: "Bumper Punks",
    creator: "NovaCade",
    handle: "thatgamer253",
    kind: "game",
    source: "community",
    blurb: "指向转向的碰碰车，可开房间联机。",
    playUrl: "https://novacade.thatgamer253.chatgpt.site/games/bumper/",
    sourceUrl: "https://novacade.thatgamer253.chatgpt.site/",
    cover: "/astra/novacade-bumper.jpg",
    coverRemote: "",
  },
  {
    id: "novacade-hexhand",
    title: "Hexhand",
    creator: "NovaCade",
    handle: "thatgamer253",
    kind: "game",
    source: "community",
    blurb: "7×7 场上的三维生物卡牌对决。",
    playUrl: "https://novacade.thatgamer253.chatgpt.site/games/hexhand/",
    sourceUrl: "https://novacade.thatgamer253.chatgpt.site/",
    cover: "/astra/novacade-hexhand.jpg",
    coverRemote: "",
  },
  {
    id: "novacade-battlerips",
    title: "BattleRips",
    creator: "NovaCade",
    handle: "thatgamer253",
    kind: "game",
    source: "community",
    blurb: "钢盘上的 1v1，用旋转打 Rip Burst。",
    playUrl: "https://novacade.thatgamer253.chatgpt.site/games/battlerips/",
    sourceUrl: "https://novacade.thatgamer253.chatgpt.site/",
    cover: "/astra/novacade-battlerips.jpg",
    coverRemote: "",
  },
  {
    id: "macos-27-simulator",
    title: "macOS 27 Simulator",
    creator: "mweinbach",
    handle: "mweinbach",
    kind: "3d",
    source: "community",
    blurb: "浏览器里的 macOS 桌面模拟。",
    playUrl: "https://macos-27-simulator.mweinbach.chatgpt.site/",
    sourceUrl: "https://macos-27-simulator.mweinbach.chatgpt.site/",
    cover: "/astra/macos-27-simulator.jpg",
    coverRemote: "",
  },
  {
    id: "felicia-last-memory",
    title: "FELICIA: The Last Memory",
    creator: "Sombra-1",
    handle: "ayx1",
    kind: "3d",
    source: "community",
    blurb: "濒死 AI 档案里的 3D 叙事，按 Identity / Fear / Hope 改空间。",
    playUrl: "https://felicia-the-last-memory.ayx1.chatgpt.site/",
    sourceUrl: "https://github.com/Sombra-1/felicia-the-last-memory",
    cover: "/astra/felicia-last-memory.jpg",
    coverRemote: "",
  },
  {
    id: "untwine",
    title: "Untwine: The Great Restoration",
    creator: "Alvan Chow",
    handle: "alvanchow",
    kind: "game",
    source: "community",
    blurb: "果园里抽枝条的可玩 demo。",
    playUrl: "https://untwine-playable-demo.alvanchow.chatgpt.site/",
    sourceUrl: "https://untwine-playable-demo.alvanchow.chatgpt.site/",
    cover: "/astra/untwine.jpg",
    coverRemote: "",
  },
  {
    id: "temple-of-eden",
    title: "Temple of Eden",
    creator: "patcoolman67",
    handle: "patcoolman67",
    kind: "game",
    source: "community",
    blurb: "有记忆的单人 5e 战役，浏览器里掷骰。",
    playUrl: "https://temple-of-eden.patcoolman67.chatgpt.site/",
    sourceUrl: "https://temple-of-eden.patcoolman67.chatgpt.site/",
    cover: "/astra/temple-of-eden.jpg",
    coverRemote: "",
  },
  {
    id: "taletree",
    title: "Taletree Kids",
    creator: "friarpuck",
    handle: "friarpuck",
    kind: "game",
    source: "community",
    blurb: "一句话生成可玩故事冒险。",
    playUrl: "https://taletree-adventure-maker.friarpuck.chatgpt.site/",
    sourceUrl: "https://taletree-adventure-maker.friarpuck.chatgpt.site/",
    cover: "/astra/taletree.jpg",
    coverRemote: "",
  },
  {
    id: "descent-flashback",
    title: "Descent: Flashback",
    creator: "dylanwoo",
    handle: "dylanwoo757047",
    kind: "game",
    source: "community",
    blurb: "六自由度矿井飞行射击致敬作。",
    playUrl: "https://descent-flashback.dylanwoo757047.chatgpt.site/",
    sourceUrl: "https://github.com/dylanwoo/descent-flashback",
    cover: "/astra/descent-flashback.jpg",
    coverRemote: "",
  },
  {
    id: "super-bash-folds",
    title: "Super Bash Folds",
    creator: "blancmathis",
    handle: "spry-crumb-3668",
    kind: "game",
    source: "community",
    blurb: "开源平台格斗，角色和关卡都是内容包。",
    playUrl: "https://super-bash-folds.spry-crumb-3668.chatgpt.site/play/index.html",
    sourceUrl: "https://github.com/blancmathis/Super_Bash_Folds",
    cover: "/astra/super-bash-folds.webp",
    coverRemote: "https://raw.githubusercontent.com/blancmathis/Super_Bash_Folds/main/docs/media/gameplay.webp",
  },
  {
    id: "redacted-sky",
    title: "The Redacted Sky",
    creator: "moonbow166",
    handle: "moonbow166",
    kind: "3d",
    source: "community",
    blurb: "把官方 UAP 档案铺进三维深空场。",
    playUrl: "https://the-redacted-sky.moonbow166.chatgpt.site/",
    sourceUrl: "https://github.com/moonbow166/the-redacted-sky",
    cover: "/astra/redacted-sky.jpg",
    coverRemote: "",
  },
  {
    id: "fire-hose-hero",
    title: "Fire Hose Hero",
    creator: "Manse",
    handle: "ran584000",
    kind: "game",
    source: "community",
    blurb: "体感浇灭火焰的旗舰小游戏。",
    playUrl: "https://fire-hose-hero.ran584000.chatgpt.site/",
    sourceUrl: "https://github.com/ahndohun/manse",
    cover: "/astra/fire-hose-hero.jpg",
    coverRemote: "",
  },
  {
    id: "manse-playground",
    title: "Manse Playground",
    creator: "Manse",
    handle: "ran584000",
    kind: "game",
    source: "community",
    blurb: "不用摄像头的体感游戏模拟器。",
    playUrl: "https://manse-showcase.ran584000.chatgpt.site/playground?provider=simulated",
    sourceUrl: "https://manse-showcase.ran584000.chatgpt.site/",
    cover: "/astra/manse-playground.jpg",
    coverRemote: "",
  },
  {
    id: "zork-underground",
    title: "Zork · Underground Empire",
    creator: "Ethan Mollick",
    handle: "emollick",
    kind: "game",
    source: "community",
    blurb: "Astra 把 1977 文本 Zork 做成第一人称 3D 动作冒险。",
    playUrl: "https://zork-underground-empire.netlify.app/",
    sourceUrl: "https://github.com/emollick/zork-underground-empire",
    cover: "/astra/zork-underground.jpg",
    coverRemote: "",
  },
  {
    id: "library-of-babel",
    title: "Library of Babel",
    creator: "Ethan Mollick",
    handle: "emollick",
    kind: "3d",
    source: "community",
    blurb: "博尔赫斯巴别图书馆的无限六角厅，可走路可搜书。",
    playUrl: "https://library-of-babel-3d.netlify.app/",
    sourceUrl: "https://github.com/emollick/library-of-babel",
    cover: "/astra/library-of-babel.jpg",
    coverRemote: "",
  },
  {
    id: "annals-kingdom",
    title: "The Annals",
    creator: "Ethan Mollick",
    handle: "emollick",
    kind: "3d",
    source: "community",
    blurb: "单文件中世纪王国：经济、王朝、战争和龙。",
    playUrl: "https://annals-kingdom.netlify.app/",
    sourceUrl: "https://github.com/emollick/annals-kingdom",
    cover: "/astra/annals-kingdom.jpg",
    coverRemote: "",
  },
  {
    id: "safari-math",
    title: "Serena's Safari Math",
    creator: "Peter G. Yang",
    handle: "petergyang",
    kind: "game",
    source: "community",
    blurb: "safari 主题数学小游戏。",
    playUrl: "https://serenas-safari-math.petergyang.chatgpt.site/",
    sourceUrl: "https://github.com/petergyang/safari-math-game",
    cover: "/astra/safari-math.jpg",
    coverRemote: "",
  },
  {
    id: "english-adventure-3d",
    title: "English Adventure 720 3D",
    creator: "arisa008",
    handle: "arisa008",
    kind: "3d",
    source: "community",
    blurb: "720 度三维英语冒险。",
    playUrl: "https://english-adventure-720-3d.arisa008.chatgpt.site/",
    sourceUrl: "https://github.com/nakahara-health/english-adventure-720-3d",
    cover: "/astra/english-adventure-3d.jpg",
    coverRemote: "",
  },
  {
    id: "mike-moonlight-run",
    title: "Mike Moonlight Run",
    creator: "rojii",
    handle: "rojii",
    kind: "game",
    source: "community",
    blurb: "月光跑酷。",
    playUrl: "https://mike-moonlight-run.rojii.chatgpt.site/",
    sourceUrl: "https://github.com/rsakao/mike-moonlight-run",
    cover: "/astra/mike-moonlight-run.jpg",
    coverRemote: "",
  },
  {
    id: "shipwright",
    title: "Shipwright",
    creator: "Kevin Whinnery",
    handle: "kevinwhinnery",
    kind: "3d",
    source: "community",
    blurb: "给 ChatGPT Sites 做的三维飞船编辑器。",
    playUrl: "https://shipwright-editor.kevinwhinnery.chatgpt.site/",
    sourceUrl: "https://github.com/kwhinnery/shipwright",
    cover: "/astra/shipwright.jpg",
    coverRemote: "",
  },
  {
    id: "simplex-studio",
    title: "Simplex Studio",
    creator: "jbayham",
    handle: "csu-bayham-2831",
    kind: "3d",
    source: "community",
    blurb: "单纯形可视化工作室。",
    playUrl: "https://simplex-studio.csu-bayham-2831.chatgpt.site/",
    sourceUrl: "https://github.com/jbayham/simplex-studio",
    cover: "/astra/simplex-studio.jpg",
    coverRemote: "",
  },
  {
    id: "grid-atlas",
    title: "GRID ATLAS",
    creator: "Matthew Berman",
    handle: "matthewberman",
    kind: "3d",
    source: "astra-review",
    blurb: "网格地图册三维界面，Astra 评测磁贴。",
    playUrl: "https://brave-tinsel-8625.here.now/",
    sourceUrl: "https://signals.forwardfuture.com/astra-review/",
    cover: "/astra/grid-atlas.jpg",
    coverRemote: "",
  },
  {
    id: "changzheng-shilu-shan",
    title: "长征诗路山",
    creator: "olixu99",
    handle: "olixu99",
    kind: "3d",
    source: "community",
    blurb: "三维长征诗词地图：山河、书法、朗诵和场景动画。",
    playUrl: "https://changzheng-shilu-shan.olixu99.chatgpt.site/",
    sourceUrl: "https://github.com/GrittingLeo/changzheng-shilu-shan",
    cover: "/astra/changzheng-shilu-shan.jpg",
    coverRemote: "",
  },
  {
    id: "motion-dungeon",
    title: "Motion Dungeon",
    creator: "dclarke1005",
    handle: "dclarke1005",
    kind: "3d",
    source: "community",
    blurb: "可编辑的 Three.js / GLSL 程序化特效时间轴工作室。",
    playUrl: "https://motion-dungeon.dclarke1005.chatgpt.site/",
    sourceUrl: "https://github.com/Valar05/motion-dungeon",
    cover: "/astra/motion-dungeon.jpg",
    coverRemote: "",
  },
  {
    id: "lijing-math-realms",
    title: "丽景数学馆",
    creator: "xiande",
    handle: "xiande",
    kind: "3d",
    source: "community",
    blurb: "交互数学观念博物馆，手稿风三维展厅。",
    playUrl: "https://lijing-math-realms.xiande.chatgpt.site/",
    sourceUrl: "https://github.com/xianxie6/lijing-math-realms",
    cover: "/astra/lijing-math-realms.jpg",
    coverRemote: "",
  },
  {
    id: "macos-27-liquid-glass",
    title: "macOS 27 Liquid Glass",
    creator: "Max Weinbach",
    handle: "max140936",
    kind: "3d",
    source: "community",
    blurb: "另一版浏览器 macOS 27，液态玻璃桌面。",
    playUrl: "https://macos-27-liquid-glass.max140936.chatgpt.site/",
    sourceUrl: "https://macos-27-liquid-glass.max140936.chatgpt.site/",
    cover: "/astra/macos-27-liquid-glass.jpg",
    coverRemote: "",
  },
  {
    id: "moonlit-forge-studio",
    title: "Moonlit Forge Studio",
    creator: "op7418",
    handle: "op7418",
    kind: "3d",
    source: "community",
    blurb: "Astra 一条流水线：Blender 建模进 Three.js 再发布站点。",
    playUrl: "https://moonlit-forge-studio.op7418.chatgpt.site/",
    sourceUrl: "https://x.com/op7418/status/2096205141187956887",
    cover: "/astra/moonlit-forge-studio.jpg",
    coverRemote: "",
  },
  {
    id: "van-goghs-town",
    title: "Van Gogh Town",
    creator: "Peter Gostev",
    handle: "petergostev",
    kind: "3d",
    source: "community",
    blurb: "Astra 把六幅梵高画拼成可走的第一人称小镇。",
    playUrl: "https://van-goghs-town.surge.sh/",
    sourceUrl: "https://x.com/petergostev/status/2095776685807346105",
    cover: "/astra/van-goghs-town.jpg",
    coverRemote: "",
  },
];
